version: latest

services:
  backend:
    build: ./backend
    volumes:
      - './backend:/app'
      - './backend/parsed_data:/app/parsed_data'
    ports:
      - '8000:8000'

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
    command: npm run dev
    ports:
      - '3000:3000'

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - './frontend/build:/usr/share/nginx/html'
    ports:
      - '80:80'
