version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - './backend:/app'
      - './backend/parsed_data:/app/database'
    ports:
      - '8000:8000'

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
      